name: antibody_quality_limitations
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - beautifulsoup4
  - requests
  - statsmodels
  - python=3.8
  - matplotlib
  - pandas
  - seaborn
  - notebook
  - xlsxwriter
  - numpy
  - scipy
  - openpyxl
  - scikit-learn
variables:
  DATA_PATH: G:\My Drive\external_data
