name: antibody_quality_limitations
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - notebook
  - xlsxwriter
  - requests
  - beautifulsoup4
  - pip
variables:
  DATA_PATH: G:\My Drive\external_data